version: "3"

services:
    db:
        container_name: kotlin_study_db
        image: mysql:5.7
        ports:
            - 3308:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: kotlin_study
            MYSQL_VERSION: 8.0.12

